export const catchErrors = error => {
  console.log(error);
};